//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nov4thYr_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment4
    {
        public int AptId { get; set; }
        public string UserId { get; set; }
        public string PatientName { get; set; }
        public string Gender { get; set; }
        public string PatientPhoneNum { get; set; }
        public string Email { get; set; }
        public string Symptoms { get; set; }
        public string Doctor { get; set; }
        public string Date { get; set; }
    }
}
