//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nov4thYr_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event1
    {
        public int id { get; set; }
        public string text { get; set; }
        public System.DateTime eventstart { get; set; }
        public System.DateTime eventend { get; set; }
    }
}
